# This is a basic workflow to help you get started with Actions

name: run on pull requests

# Controls when the action will run. 

on:
  pull_request_review_comment:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job runs"
